Clean up retries

diff --git a/.github/workflows/network-check.yaml b/.github/workflows/network-check.yaml
--- a/.github/workflows/network-check.yaml
+++ b/.github/workflows/network-check.yaml
@@ -40,4 +40,16 @@ jobs:
         run: |
           cd tests/api_tests
           custom_network=$(echo ${{ matrix.network }} | xargs | sed -E 's/^\s*.*:\/\///g' | sed 's:/*$::') && sed -i "0,/REPLACE/s//$custom_network/" './Environments/custom.postman_environment.json'
-          newman run "./0chain-smoke-test.json" -e "./Environments/custom.postman_environment.json" -r cli --color on || (echo "RETRYING..." && sleep 30 && newman run "./0chain-smoke-test.json" -e "./Environments/custom.postman_environment.json" -r cli --color on)
+
+          counter=1;
+          exit_code=1;
+          while [ $counter -lt 6 ] && [ $exit_code -eq 1 ]; do
+            echo "Executing smoke tests attempt [$counter/5]" && ((counter=counter+1));
+            exit_code=0
+            newman run "./0chain-smoke-test.json" -e "./Environments/custom.postman_environment.json" -r cli --color on || (exit_code=1 && sleep 30)
+          done
+
+          if [ $counter -eq 6 ]; then
+            echo "Smoke tests failed for network [${{ matrix.network }}]"
+            exit 1
+          fi
